let string_of_label(l:SyntaxLabel.t)=
  match l with
  |ConstantValue->"ConstantValue"
  |VariableDeclarations->"VariableDeclarations"
  |VariableDeclaration->"VariableDeclaration"
  |ProcedureDeclaration->"ProcedureDeclaration"
  |ProgramRoot->"ProgramRoot"
  |Block->"Block"
  |Proposition->"Proposition"
  |Expression->"Expression"
  |VariableAssign->"VariableAssign"
  |ConstOrVarRead->"ConstOrVarRead"
  |VariableAssignFromReadln->"VariableAssignFromReadln"
  |ProcedureNameDeclaration->"ProcedureNameDeclaration"
  |ProcedureNameCall->"ProcedureNameCall"
  |ConstantNameDeclaration->"ConstantNameDeclaration"
  |Term->"Term"
  |AssignationProposition->"AssignationProposition"
  |IfProposition->"IfProposition"
  |WhileProposition->"WhileProposition"
  |Factor->"Factor"
  |LiteralInteger->"LiteralInteger"
  |Negation->"Negation"
  |FactorOperation->"FactorOperation2"
  |TermOperation->"TermOperation"
  |Comparator->"Comparator"
  |WriteLineProposition->"WriteLineProposition"
  |WriteExpression->"WriteExpression"