type t=
|ConstantNameDeclaration
|ConstantValue
|VariableDeclarations
|VariableDeclaration
|ProcedureDeclaration
|ProgramRoot
|Block
|Proposition
|Expression
|VariableAssign
|ConstOrVarRead
|VariableAssignFromReadln
|ProcedureNameDeclaration
|ProcedureNameCall
|Term
|AssignationProposition
|IfProposition
|WhileProposition
|Factor
|LiteralInteger
|Negation
|FactorOperation
|TermOperation